url: http://freifunk.in-kiel.de/

destination: _site

community:
  # Metadata
  name: "Kiel"
  meta: "Freifunk Nord"
  country: "DE"

  # Custom URLs
  url_wiki:  "https://wiki.freifunk.in-kiel.de/"
  url_webchat: "https://riot.eclabs.de/#/room/#hackint_#ffki:matrix.eclabs.de"
  url_graph: "https://grafahana.freifunk.in-kiel.de/"
  url_meshviewer: "http://mesh.freifunk.in-kiel.de/"

  url_mailman: "https://lists.in-kiel.de/cgi-bin/mailman/listinfo/freifunk"

  url_firmware: "https://freifunk.in-kiel.de/firmware.html"

  url_mailsender: "http://freifunk.discovibration.de/freifunk-mail.php"
  url_nodealarm: "http://freifunk.discovibration.de/freifunk-nodewatcher.php"

  # Mail Contacts
  mail_info: "freifunk@lists.in-kiel.de"
  mail_keys: "freifunk-keys@lists.in-kiel.de"
  mail_discussion: "freifunk@lists.in-kiel.de"

  # Other Contacts
  #sip: ["space@sip.ffki"] # Optional
  twitter: "ff_Kiel" # Optional
  irc: "ffki"

  # GPS
  geo_lat: 54.4
  geo_lon: 10.1

firmware:
  base: "http://freifunk.in-kiel.de/firmware/stable/"
  type: "gluon"

  # URL to the site repo (gitweb,github...)
  gluon_site: "http://git.freifunk.in-kiel.de/ffki-site/"

  # Path to local checkout of the site repo
  gluon_site_dir: "/opt/site-ffki/"

tld:
  label: "ffki"
  ns:
    - "10.116.136.1"
    - "fda1:384a:74de:4242::ff01"
    - "10.116.168.1"
    - "fda1:384a:74de:4242::ff02"
    - "10.116.144.1"
    - "fda1:384a:74de:4242::ff03"
    - "10.116.176.1"
    - "fda1:384a:74de:4242::ff05"
    - "10.116.184.1"
    - "fda1:384a:74de:4242::ff06"
    - "10.116.192.1"
    - "fda1:384a:74de:4242::ff07"
